### ISSUE TITLE
How can add confusion matrix to an existing experiment?

### ISSUE THREAD

**Issue by ali3assi** [neptune-ai/neptune-examples#46]
My question is more related to the use of Neptune . 
In fact I trained my model and now I want to predict on the test set. I already saved the best model. the experiment is succeed in Neptune .
So, ho can fetch an existing experiment from Neptune and log the confusion matrix?

**Comment by jakubczakon** [comment]
Hi @ali3assi,

Here is a [docs page that shows that](https://docs.neptune.ai/logging-and-managing-experiment-results/updating-existing-experiment.html). 

Basically you can do:

import neptune

```python
# Get project
project = neptune.init('my_workspace/my_project')

# Get experiment object for appropriate experiment, here 'SHOW-2066'
my_exp = project.get_experiments(id='SHOW-2066')[0]

# Log confusion matrix
my_exp.log_image('diagnostic charts', fig)
```

I hope this helps. 

By the way there is a separate repo for [neptune-client](https://github.com/neptune-ai/neptune-client).

**Comment by jakubczakon** [comment]
Did it help @ali3assi ?
