### ISSUE TITLE
Neptune + TensorBoard cannot convert TensorBoard logs to Neptune experiments

### ISSUE THREAD

**Issue by kaplansinan** [neptune-ai/neptune-examples#52]
Hei, 

I have tensorboard log files logged from an experiment and I wanted to convert it to neptune experiments. However, when I try to do it, I got following  error from the command  "! neptune tensorboard output/logs/20210528-101934": 

**>`Cannot load run from file 'events.out.tfevents.1622186389.keras.22115.0'. Expecting value: line 1 column 1 (char 0)`**

My stack is:
- tensorboard==2.5.0
- neptune-client==0.9.15
- neptune-tensorboard==0.5.1

**Comment by aniezurawski** [comment]
Was it an exception or some warning printed on stderr? If it's exception could you share full traceback?

**Comment by kaplansinan** [comment]
there is no clear message on the terminal. Here is the screenshot from the terminal.
<img width="963" alt="debug" src="https://user-images.githubusercontent.com/7412912/120323694-6e17f180-c2ee-11eb-9182-4e52791d6623.png">


Also, you can find a tensorboard log file via following link and try it: https://drive.google.com/drive/folders/1fkV3ibj6yETDSYZZtVukwkQP7Jhu-bxP?usp=sharing

**Comment by Raalsky** [comment]
Hi @kaplansinan !
Could you please provide your current `locale` settings? (output of `locale` command if your work with Posix system) or just type:
```
> echo $LANGUAGE
> echo $LANG
> echo $LC_ALL
```
Potential solution is to set your current locale settings to `UTF-8` especially:
```
> export LANGUAGE=en_US.UTF-8
> export LANG=en_US.UTF-8
> export LC_ALL=en_US.UTF-8
> export PYTHONIOENCODING=utf8
```

**Comment by kaplansinan** [comment]
Hi @Raalsky this is the output from `locale` command:
<img width="719" alt="debug2" src="https://user-images.githubusercontent.com/7412912/120794882-75830900-c541-11eb-9990-bf0fc5547cc1.png">

**Comment by Raalsky** [comment]
Ok. Could you please provide your version of `tensorflow`?
