### ISSUE TITLE
results_summary displays more layers than actual number of layers

### ISSUE THREAD

**Issue by saraelmekkaoui** [neptune-ai/neptune-examples#53]
Hi,

When trying out the Keras Tuner notebook example, trials summaries return number of layers different from the list of units per layer. As shown in the example below, the number of layers is 4 but numbers of units are displayed for 19 layers. 

How can I fix it?

Thanks!

![image](https://user-images.githubusercontent.com/48381878/129621188-769f8f88-f221-41c9-95be-72faa6672136.png)

**Comment by kamil-kaczmarek** [comment]
Hey @saraelmekkaoui,

Thanks a lot for the links :)

NeptuneLogger for Keras tuner takes the trial status and logs it to neptune. The tuning logic itself returns the units information. I would recommend to refer to the keras tuner docs to check how that info is determined.

Seems that you are using neptune-contrib which is now in the maintenance only stage.
Similarly you use the legacy API (example is: `neptune.create_experiment(name='exp-1')`). I recommend to use the latest version of the `neptune-client` as legacy api is in the maintenance only stage.
Here is the docs that will help you [migrate to the neptune.new](https://docs.neptune.ai/migration-guide).

 For the new API, keras tuner is now in progress in our engineering team.

BTW: it's not recommended to put the api token as a plain string in the notebooks. Instead you can try to do this instead: 
```
from getpass import getpass
api_token = getpass("Enter your private Neptune API token: ")
```

Please let me know if it helps :)
